stages:
  - build

#===============================================================================
# Build lib60870
#===============================================================================
test-systest:
  image: debian:9
  stage: build
  script:
    - |
      n=6; row="";
      for(( i=0; i<n; i++ )); do row="$row "; done; row="${row%?}*"; for(( i=0; i<n; i++ )); do echo "$row"; row="${row#?}**"; done
  tags:
    - docker
