stages:
  - build

#===============================================================================
# Build lib60870
#===============================================================================
test-systest:
  image: debian:9
  stage: build
  script:
    - apt update
    - apt install -y g++ gcc cmake make git make wget python3 python3-pip
    - mkdir /tmp/build
    - cd /tmp/build && git clone https://github.com/mz-automation/lib60870.git
    - cd /tmp/build/lib60870/lib60870-C/ && mkdir build && cd build && cmake .. -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ && make install
    - ls /usr/local/lib
    - ls -a
    - pip3 install twisted
    - cd /builds/i1729van/py60870server/ && python3 __main__.py
    - |
        n=30; row=""; for(( i=0; i<n; i++ )); do row="$row "; done; row="${row%?}*"; for(( i=0; i<n; i++ )); do echo "$row"; row="${row#?}**"; done
  tags:
    - docker
